### ISSUE TITLE
[Not a bug] Is there a roadmap or list of active issues? You mentioned this repo is a work in progress, i'd like to help

### ISSUE THREAD

**Issue by jeffward01** [microcompiler/backblaze#14]
Hello!

Thanks for the AMAZING library, its easier than working with CLI tools, then parsing the output and boxing the JSON into objects! **YOU ARE A HERO**!

You mentioned this is a Work in Progress, I was wondering a few things:

.)  Do you have a list of features like:L
* This is done
* This is working and unstable, testing required
* This is under-developement
* This is todo

I would love to contribute how I can. The list will help alot so that I am not blindly working with the codebase.

Thanks again!

**Comment by microcompiler** [comment]
Thank you for the kind words.   I would appreciate any contributions you are willing to make.  All I ask is that you  make a PR for the changes or feature, include a test case for it, then submit it.  

I do not have a list other then the open issues marked as “features”.   I do have a couple wishlist items that I’ve had in the back of my mind for sometime.   From the open features list a couple individuals have asked to be able to manage the uploads and downloads as streams instead of a file. 

* A power shell command application.  Their are plenty of command line application but no true power shell applications (however I have not looked recently).   
https://devblogs.microsoft.com/powershell/depending-on-the-right-powershell-nuget-package-in-your-net-project/
https://www.red-gate.com/simple-talk/development/dotnet-development/using-c-to-create-powershell-cmdlets-the-basics/

* Create a MVC website that is a simple file manager for D2 storage.

**Comment by microcompiler** [comment]
@jeffward01 did you have any particular areas you wanted to enhance.
